export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Link from "next/link"
import Navbar from "./navbar"
import "./layoutstyles.css"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
         <Navbar/>
        {children}
        </body>
    </html>
  )
}
